# Generated by Django 3.1.4 on 2020-12-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swergit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.TextField(blank=True, null=True),
        ),
    ]
