# Generated by Django 3.1.4 on 2020-12-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swergit', '0002_post_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
