# Generated by Django 3.1.4 on 2020-12-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swergit', '0003_auto_20201231_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
