# Generated by Django 3.1.4 on 2021-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swergit', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
