# Generated by Django 3.1.4 on 2021-03-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swergit', '0006_post_subimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subimage',
        ),
    ]
